"""
Phase 26 — DEMO ARGO-like profiles. SYNTHETIC. NOT REAL OBSERVATIONS.

Used only when real ARGO data is not available, to exercise the validation
pipeline end to end. Everything this module writes is labelled as
synthetic in five independent places, so stripping any one of them
(a sidecar, a header) does not make the data look real:

1. the file name contains ``SYNTHETIC``;
2. the CSV starts with ``#`` comment lines saying so;
3. every row has ``provenance = DEMO_SYNTHETIC_ARGO``;
4. every float id starts with ``DEMO_``;
5. a ``.meta.json`` sidecar with ``data_mode`` and a disclaimer.

`ArgoProfileSet.is_demo` fires on any of 3-5, and every report/plot/CSV
produced from such a set says so.

What is generated
------------------
Floats drifting on a random walk inside the NEER domain, a profile every
~10 days, each on irregular ARGO-like pressure levels (dense near the
surface, sparser at depth, some profiles only to ~500 or ~1000 dbar), with
a tanh-thermocline temperature field, a seasonal cycle, a per-profile
"eddy" offset and instrument noise. Deliberately included, so every
branch of the pipeline runs: a few QC-flagged spikes, a few profiles too
short to use, some positions off the grid (outside the domain, or on land
cells when a mask is supplied) and some outside the NEER time axis.

The temperature field is a closed-form function, unrelated to the NEER
demo tensors and to any real ocean — the resulting error numbers mean
nothing about NEER or the Indian Ocean.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Tuple, Union

import numpy as np

from src.argo_validation.matching import NeerGrid
from src.argo_validation.predictions import ORIGIN_DEMO_STAND_IN, NeerPredictions
from src.argo_validation.profiles import DATA_MODE_DEMO, DEMO_FLOAT_PREFIX, pressure_to_depth

PathLike = Union[str, Path]

DISCLAIMER = (
    "SYNTHETIC DEMO ARGO-like profiles generated by src/argo_validation/demo.py from closed-form "
    "formulas and a seeded random number generator. They are NOT ARGO observations, were never "
    "measured by any float, and must not be used for scientific validation or reported as such."
)
DEFAULT_DEMO_FILENAME = "demo_argo_profiles_SYNTHETIC.csv"


def analytic_temperature(depth_m, lat, month_fraction) -> np.ndarray:
    """Closed-form synthetic T(z) [degC] — warm surface, tanh thermocline,
    seasonal cycle. `month_fraction` is the day-of-year / 365 (0..1)."""
    z = np.asarray(depth_m, dtype=float)
    season = 1.2 * np.cos(2 * np.pi * (month_fraction - 0.4))
    sst = 28.6 - 0.12 * (lat - 5.0) + season
    z_th = 90.0 + 1.5 * (lat - 5.0)
    deep = 4.3
    return deep + (sst - deep) * 0.5 * (1.0 - np.tanh((z - z_th) / 55.0)) + 0.6 * np.exp(-z / 400.0)


def _pressure_levels(rng: np.random.Generator, max_p: float) -> np.ndarray:
    parts = [np.arange(5.0, 100.0, rng.uniform(4.0, 10.0)),
             np.arange(100.0, min(max_p, 400.0), rng.uniform(10.0, 25.0)),
             np.arange(400.0, min(max_p, 1000.0), rng.uniform(25.0, 50.0))]
    if max_p > 1000:
        parts.append(np.arange(1000.0, max_p + 1, rng.uniform(50.0, 100.0)))
    p = np.concatenate(parts)
    return p[p <= max_p]


def generate_demo_argo(
    output_path: PathLike,
    grid: NeerGrid,
    *,
    n_floats: int = 24,
    seed: int = 42,
) -> Path:
    """Write a clearly-labelled SYNTHETIC ARGO-like CSV (+ sidecar) covering `grid`'s
    domain and time range. Returns the CSV path."""
    rng = np.random.default_rng(seed)
    output_path = Path(output_path)
    if "SYNTHETIC" not in output_path.name.upper():
        raise ValueError("demo ARGO files must have 'SYNTHETIC' in the file name")
    output_path.parent.mkdir(parents=True, exist_ok=True)

    lat_lo, lat_hi = float(grid.lat.min()), float(grid.lat.max())
    lon_lo, lon_hi = float(grid.lon.min()), float(grid.lon.max())
    t0 = grid.time.min().astype("datetime64[D]")
    t1 = (grid.time.max().astype("datetime64[M]") + 1).astype("datetime64[D]")  # end of last month
    span_days = int((t1 - t0).astype(int))

    def ocean_point() -> Tuple[float, float]:
        for _ in range(500):
            la, lo = rng.uniform(lat_lo, lat_hi), rng.uniform(lon_lo, lon_hi)
            i, j = int(np.argmin(np.abs(grid.lat - la))), int(np.argmin(np.abs(grid.lon - lo)))
            if grid.ocean_mask is None or grid.ocean_mask[i, j]:
                return la, lo
        return (lat_lo + lat_hi) / 2, (lon_lo + lon_hi) / 2

    rows = []
    for f in range(n_floats):
        float_id = f"{DEMO_FLOAT_PREFIX}_{f + 1:04d}"
        lat, lon = ocean_point()
        day = int(rng.integers(0, max(span_days // 3, 1)))
        max_p = float(rng.choice([500.0, 1000.0, 2000.0], p=[0.15, 0.35, 0.5]))
        for cycle in range(1, 1000):
            day += int(rng.integers(9, 12))
            if day >= span_days + 20:
                break
            # random-walk drift, kept inside the ocean where possible
            nlat, nlon = lat + rng.normal(0, 0.35), lon + rng.normal(0, 0.45)
            i, j = int(np.argmin(np.abs(grid.lat - nlat))), int(np.argmin(np.abs(grid.lon - nlon)))
            if lat_lo <= nlat <= lat_hi and lon_lo <= nlon <= lon_hi and (
                grid.ocean_mask is None or grid.ocean_mask[i, j]
            ):
                lat, lon = nlat, nlon
            plat, plon = lat, lon
            # deliberate off-grid positions to exercise rejection paths (~3%)
            r = rng.random()
            if r < 0.015:
                plat = lat_hi + rng.uniform(1.0, 4.0)
            elif r < 0.03 and grid.ocean_mask is not None and (~grid.ocean_mask).any():
                ii, jj = np.argwhere(~grid.ocean_mask)[rng.integers(0, int((~grid.ocean_mask).sum()))]
                plat, plon = float(grid.lat[ii]), float(grid.lon[jj])

            when = t0 + np.timedelta64(day, "D")
            time = np.datetime64(when, "s") + np.timedelta64(int(rng.integers(0, 86400)), "s")
            doy = (when - when.astype("datetime64[Y]")).astype(int) / 365.0

            pmax = max_p if rng.random() > 0.08 else float(rng.choice([30.0, 40.0]))  # a few truncated casts
            p = _pressure_levels(rng, pmax)
            depth = pressure_to_depth(p, plat)
            eddy = rng.normal(0, 0.8) * np.exp(-depth / 300.0)
            temp = analytic_temperature(depth, plat, doy) + eddy + rng.normal(0, 0.02, depth.size)
            qc = np.full(depth.size, "1", dtype="<U1")
            spikes = rng.random(depth.size) < 0.02
            temp = np.where(spikes, temp + rng.choice([-6.0, 7.0]), temp)
            qc[spikes] = "4"

            for k in range(depth.size):
                rows.append((float_id, cycle, str(np.datetime64(time, "s")), plat, plon,
                             p[k], temp[k], qc[k], "1", "1"))

    with open(output_path, "w", encoding="utf-8", newline="") as fh:
        fh.write("# DEMO_SYNTHETIC_ARGO -- SYNTHETIC DATA, NOT REAL ARGO OBSERVATIONS\n")
        fh.write("# Generated by src/argo_validation/demo.py from formulas + a seeded RNG.\n")
        fh.write("# Pipeline demonstration only. Never report results from this file as validation.\n")
        fh.write("float_id,cycle,time,lat,lon,pres_dbar,temp_c,temp_qc,position_qc,time_qc,provenance\n")
        for r in rows:
            fh.write(f"{r[0]},{r[1]},{r[2]},{r[3]:.4f},{r[4]:.4f},{r[5]:.1f},{r[6]:.4f},{r[7]},{r[8]},{r[9]},"
                     f"{DATA_MODE_DEMO}\n")

    import json

    meta: Dict[str, Any] = {
        "data_mode": DATA_MODE_DEMO,
        "disclaimer": DISCLAIMER,
        "generator": "src/argo_validation/demo.py",
        "seed": seed,
        "n_floats": n_floats,
        "n_rows": len(rows),
        "generated_at": datetime.utcnow().isoformat(timespec="seconds") + "Z",
    }
    with open(output_path.with_suffix(".meta.json"), "w", encoding="utf-8") as fh:
        json.dump(meta, fh, indent=2)
    return output_path


def demo_stand_in_predictions(grid: NeerGrid) -> NeerPredictions:
    """A **stand-in that is not NEER**: the closed-form demo climate averaged
    over the domain, per month. It exists so a demo run has *something* on
    the prediction side when no trained checkpoint is available; it is
    labelled `demo_stand_in_NOT_NEER` everywhere it appears."""
    lat_mean = float(np.mean(grid.lat))
    doy = np.array(
        [(t.astype("datetime64[D]") - t.astype("datetime64[Y]")).astype(int) / 365.0 for t in grid.time]
    )
    temp = np.vstack([analytic_temperature(grid.depth, lat_mean, d) for d in doy])
    return NeerPredictions(
        time=grid.time,
        depth_m=np.asarray(grid.depth, dtype=float),
        temperature_c=temp,
        origin=ORIGIN_DEMO_STAND_IN,
        source="src/argo_validation/demo.py::demo_stand_in_predictions",
        notes=["NOT a NEER prediction: closed-form demo climate, for pipeline demonstration only."],
    )