"""
Phase 26 — ARGO profile model, quality control and pressure→depth.

An ARGO profile is one CTD cast from one float: a position, a time, and a
temperature-vs-pressure trace on irregular levels. This module holds the
in-memory representation (`ArgoProfile`, `ArgoProfileSet`) and the two
pure functions everything downstream needs: `pressure_to_depth` and
`clean_profile` (QC).

Provenance is part of the type
-------------------------------
`ArgoProfileSet.data_mode` says what the profiles *are*:

* ``DEMO_SYNTHETIC_ARGO`` — generated by `src.argo_validation.demo`. Not
  observations. Everything reported from it is labelled as a pipeline
  demonstration, never as validation.
* ``ARGO_USER_SUPPLIED`` — a file the user pointed us at. This code cannot
  verify that a CSV really came from ARGO floats, so it says
  "user-supplied" rather than asserting authenticity.

`ArgoProfileSet.is_demo` is deliberately fail-safe: any evidence of demo
provenance (data_mode, a disclaimer, or a ``DEMO`` float-id prefix) makes
the whole set demo.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Sequence, Tuple

import numpy as np

DATA_MODE_DEMO = "DEMO_SYNTHETIC_ARGO"
DATA_MODE_USER = "ARGO_USER_SUPPLIED"

DEMO_FLOAT_PREFIX = "DEMO"

#: ARGO QC flag semantics (reference table 2): 1 good, 2 probably good,
#: 3 probably bad, 4 bad, 5 changed, 8 estimated, 9 missing, 0 not QC'd.
DEFAULT_ACCEPT_VALUE_QC: Tuple[str, ...] = ("1",)
#: Position/time flags that disqualify a whole profile when supplied.
REJECT_POSITION_TIME_QC: Tuple[str, ...] = ("3", "4", "9")

#: Physically plausible in-situ temperature range, degC.
TEMP_RANGE_C: Tuple[float, float] = (-2.5, 40.0)


# --------------------------------------------------------------------------
# Pressure -> depth
# --------------------------------------------------------------------------


def pressure_to_depth(pressure_dbar: np.ndarray, lat_deg: float) -> np.ndarray:
    """Depth in metres from sea pressure in dbar (Saunders & Fofonoff 1976,
    as in UNESCO/SEAWATER `sw_dpth`; latitude-dependent gravity).

    Standard-ocean (0 degC, 35 psu) column, which is what the formula
    assumes; the difference from a full TEOS-10 conversion is metres at
    2000 dbar, far below the 15-level model grid this feeds.
    """
    p = np.asarray(pressure_dbar, dtype=float)
    x = np.sin(np.deg2rad(abs(float(lat_deg)))) ** 2
    grav = 9.780318 * (1.0 + (5.2788e-3 + 2.36e-5 * x) * x) + 2.184e-6 * 0.5 * p
    num = ((((-1.82e-15 * p + 2.279e-10) * p - 2.2512e-5) * p + 9.72659) * p)
    return num / grav


# --------------------------------------------------------------------------
# Containers
# --------------------------------------------------------------------------


@dataclass(frozen=True)
class ArgoProfile:
    """One ARGO temperature profile, as read (before QC).

    Exactly one of `depth_m` / `pressure_dbar` needs to be given; if only
    pressure is present depth is derived from it at the profile latitude.
    `temperature_qc` is `None` when the source carried no QC flags — the
    pipeline then keeps every finite value and counts the profile as
    "no QC information" in the report rather than pretending it was checked.
    """

    float_id: str
    cycle: int
    time: np.datetime64
    lat: float
    lon: float
    temperature_c: np.ndarray
    depth_m: Optional[np.ndarray] = None
    pressure_dbar: Optional[np.ndarray] = None
    temperature_qc: Optional[np.ndarray] = None
    position_qc: Optional[str] = None
    time_qc: Optional[str] = None
    adjusted: Optional[bool] = None  # True if delayed-mode/adjusted values were used

    @property
    def profile_id(self) -> str:
        return f"{self.float_id}:{self.cycle}"

    def depths(self) -> np.ndarray:
        if self.depth_m is not None:
            return np.asarray(self.depth_m, dtype=float)
        if self.pressure_dbar is not None:
            return pressure_to_depth(self.pressure_dbar, self.lat)
        raise ValueError(f"profile {self.profile_id} has neither depth_m nor pressure_dbar")


@dataclass
class ArgoProfileSet:
    profiles: List[ArgoProfile]
    data_mode: str = DATA_MODE_USER
    source: Optional[str] = None
    disclaimer: Optional[str] = None
    notes: List[str] = field(default_factory=list)

    @property
    def n_profiles(self) -> int:
        return len(self.profiles)

    @property
    def n_floats(self) -> int:
        return len({p.float_id for p in self.profiles})

    @property
    def is_demo(self) -> bool:
        mode = str(self.data_mode).upper()
        if "DEMO" in mode or "SYNTHETIC" in mode:
            return True
        if self.disclaimer and "SYNTHETIC" in self.disclaimer.upper():
            return True
        return any(str(p.float_id).upper().startswith(DEMO_FLOAT_PREFIX) for p in self.profiles)


# --------------------------------------------------------------------------
# QC
# --------------------------------------------------------------------------

# Reasons a whole profile is rejected. Kept as constants: they are keys in
# the JSON report, so they must not drift.
REJECT_NO_TIME = "missing_or_invalid_time"
REJECT_NO_POSITION = "missing_or_invalid_position"
REJECT_BAD_POSITION_QC = "bad_position_qc"
REJECT_BAD_TIME_QC = "bad_time_qc"
REJECT_TOO_FEW_LEVELS = "too_few_valid_levels_after_qc"


@dataclass(frozen=True)
class CleanProfile:
    """A profile after QC: finite, plausible, depth-sorted, de-duplicated."""

    source: ArgoProfile
    depth_m: np.ndarray
    temperature_c: np.ndarray
    n_levels_raw: int
    n_levels_dropped_qc: int
    n_levels_dropped_range: int
    has_qc_info: bool


def clean_profile(
    profile: ArgoProfile,
    *,
    accept_qc: Sequence[str] = DEFAULT_ACCEPT_VALUE_QC,
    min_levels: int = 5,
    temp_range: Tuple[float, float] = TEMP_RANGE_C,
) -> Tuple[Optional[CleanProfile], Optional[str]]:
    """Apply profile- and level-level QC. Returns `(clean, None)` or
    `(None, reason)` — never a silently-repaired profile.

    Levels are dropped for: non-finite depth/temperature, a QC flag outside
    `accept_qc` (when flags exist), or a temperature outside `temp_range`.
    Remaining levels are sorted by depth; duplicate depths are averaged
    (real profiles occasionally repeat a pressure), and negative depths
    are dropped.
    """
    if np.isnat(profile.time):
        return None, REJECT_NO_TIME
    if not (np.isfinite(profile.lat) and np.isfinite(profile.lon)) or abs(profile.lat) > 90:
        return None, REJECT_NO_POSITION
    if profile.position_qc is not None and str(profile.position_qc) in REJECT_POSITION_TIME_QC:
        return None, REJECT_BAD_POSITION_QC
    if profile.time_qc is not None and str(profile.time_qc) in REJECT_POSITION_TIME_QC:
        return None, REJECT_BAD_TIME_QC

    temp = np.asarray(profile.temperature_c, dtype=float)
    depth = np.asarray(profile.depths(), dtype=float)
    if depth.shape != temp.shape:
        raise ValueError(
            f"profile {profile.profile_id}: depth {depth.shape} and temperature {temp.shape} differ"
        )
    n_raw = int(temp.size)

    keep = np.isfinite(temp) & np.isfinite(depth) & (depth >= 0.0)
    has_qc = profile.temperature_qc is not None
    n_qc_dropped = 0
    if has_qc:
        flags = np.asarray(profile.temperature_qc).astype(str)
        if flags.shape != temp.shape:
            raise ValueError(f"profile {profile.profile_id}: QC flags shape {flags.shape} != {temp.shape}")
        accepted = np.isin(flags, [str(a) for a in accept_qc])
        n_qc_dropped = int((keep & ~accepted).sum())
        keep &= accepted

    lo, hi = temp_range
    in_range = (temp >= lo) & (temp <= hi)
    n_range_dropped = int((keep & ~in_range).sum())
    keep &= in_range

    depth, temp = depth[keep], temp[keep]
    if depth.size < min_levels:
        return None, REJECT_TOO_FEW_LEVELS

    order = np.argsort(depth, kind="stable")
    depth, temp = depth[order], temp[order]
    uniq, inverse = np.unique(depth, return_inverse=True)
    if uniq.size != depth.size:
        temp = np.bincount(inverse, weights=temp) / np.bincount(inverse)
        depth = uniq
        if depth.size < min_levels:
            return None, REJECT_TOO_FEW_LEVELS

    return (
        CleanProfile(
            source=profile,
            depth_m=depth,
            temperature_c=temp,
            n_levels_raw=n_raw,
            n_levels_dropped_qc=n_qc_dropped,
            n_levels_dropped_range=n_range_dropped,
            has_qc_info=has_qc,
        ),
        None,
    )


def profile_summary(profiles: ArgoProfileSet) -> Dict[str, Any]:
    times = np.array([p.time for p in profiles.profiles if not np.isnat(p.time)])
    return {
        "n_profiles": profiles.n_profiles,
        "n_floats": profiles.n_floats,
        "time_range": None if times.size == 0 else [str(times.min()), str(times.max())],
        "data_mode": profiles.data_mode,
        "source": profiles.source,
    }