"""
Synthetic demo ocean dataset generator for NEER — Phase 04.

Generates a deterministic, entirely SYNTHETIC ocean dataset over the
project's target domain (5N-30N, 45E-105E, 0.25 deg — configs/base.yaml)
and depth levels (0..1000 m, 15 levels — configs/base.yaml), for use as a
lightweight stand-in while no real satellite/ARGO data pipeline exists.

Variables generated (all on the shared NEER grid from src/data/grid.py):
    sst            (time, lat, lon)         Sea Surface Temperature   [degC]
    sss            (time, lat, lon)         Sea Surface Salinity      [psu]
    sla            (time, lat, lon)         Sea Level Anomaly         [m]
    u_current      (time, lat, lon)         Zonal surface current     [m/s]
    v_current      (time, lat, lon)         Meridional surface current[m/s]
    u_wind         (time, lat, lon)         Zonal wind                [m/s]
    v_wind         (time, lat, lon)         Meridional wind           [m/s]
    subsurface_temp(time, depth, lat, lon)  Subsurface temperature    [degC]
    land_mask      (lat, lon)               True = ocean, False = land

The fields are built from simple, deterministic, physically-*motivated*
components (climatological gradients, an idealised monsoon seasonal
cycle, mesoscale-eddy-like Gaussian anomalies, an approximate geostrophic
relation between SLA and currents, a tanh thermocline profile) plus
seeded random noise and gaps. They are designed to *look* like plausible
ocean fields for demoing pipelines/UI end-to-end — they are NOT measured,
reanalyzed, or physically simulated data of any kind.

===========================================================================
IMPORTANT — DATA PROVENANCE
===========================================================================
This dataset is 100% synthetic. It is generated from closed-form formulas
and a seeded pseudo-random number generator (seed=42 by default, from
configs/base.yaml -> demo.seed). It must NEVER be described, labeled, or
used as if it were real satellite, ARGO float, reanalysis, or any other
kind of observational or scientifically validated data. Every output file
carries `"data_mode": "DEMO_SYNTHETIC"` plus an explicit disclaimer in its
metadata for exactly this reason. Do not strip that metadata downstream.
===========================================================================

Usage
-----
    python scripts/create_demo_data.py
    python scripts/create_demo_data.py --n-time 12 --seed 42 --overwrite
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Dict, Tuple

import numpy as np

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from src.data.grid import OceanGrid, create_ocean_grid  # noqa: E402
from src.utils.config import DomainConfig, load_config  # noqa: E402
from src.utils.logging import get_logger  # noqa: E402

logger = get_logger("neer.create_demo_data")

DATA_MODE = "DEMO_SYNTHETIC"
DISCLAIMER = (
    "This dataset is entirely SYNTHETIC. It was generated by "
    "scripts/create_demo_data.py from closed-form formulas and seeded "
    "random noise. It is NOT satellite data, NOT ARGO float data, NOT "
    "reanalysis, and has NOT undergone any scientific validation. It "
    "exists solely to exercise the NEER pipeline/UI end-to-end before "
    "real data is integrated. Do not use it for any scientific purpose."
)

EARTH_RADIUS_M = 6_371_000.0
EARTH_OMEGA = 7.2921159e-5  # rad/s, Earth's rotation rate
GRAVITY = 9.81  # m/s^2
DEFAULT_START_DATE = datetime(2020, 1, 15, tzinfo=timezone.utc)
DEFAULT_N_TIME = 24  # monthly snapshots -> two full seasonal cycles


# ---------------------------------------------------------------------------
# Land/ocean mask
# ---------------------------------------------------------------------------


def build_land_ocean_mask(lat_grid: np.ndarray, lon_grid: np.ndarray) -> np.ndarray:
    """Build a deliberately SIMPLIFIED/SCHEMATIC ocean mask for the domain.

    This is a hand-built geometric approximation of the broad Arabian
    Sea / Bay of Bengal / Indian-peninsula coastline layout used only to
    give the synthetic dataset a plausible land/ocean pattern to mask
    against. It is NOT a real coastline product and must not be treated
    as one.

    Returns
    -------
    np.ndarray of bool, shape (n_lat, n_lon): True = ocean, False = land.
    """
    lat = lat_grid
    lon = lon_grid
    land = np.zeros(lat.shape, dtype=bool)

    # Above ~25.5N the domain is dominated by the Iranian/Pakistani/Tibetan
    # landmass, with only a narrow Gulf-of-Oman-like taper of ocean left.
    high_lat_land = lat > 25.5
    oman_taper = (lat > 24.0) & (lat <= 26.5) & (lon >= 56.0) & (lon <= 68.0)
    land |= high_lat_land & ~oman_taper

    # Arabian Peninsula (Yemen/Oman/Saudi coast): a wedge along the western
    # edge of the domain, tapering as latitude decreases.
    arabia = (lat > 12.0) & (lon <= (58.0 - 0.35 * (lat - 12.0)))
    land |= arabia

    # Horn of Africa (Somalia coast): a wedge in the low-lon, low-lat corner.
    horn_of_africa = (lat <= 12.0) & (lon <= (46.5 + 0.35 * lat))
    land |= horn_of_africa

    # Indian peninsula: a wedge narrowing to a point near Cape Comorin
    # (~8N, 77E) and widening northward into the subcontinent, splitting
    # the Arabian Sea (west) from the Bay of Bengal (east).
    in_peninsula_lat = (lat >= 8.0) & (lat <= 25.5)
    lat_c = np.clip(lat, 8.0, 24.0)
    west_bound = 77.0 - (77.0 - 68.0) * (lat_c - 8.0) / (24.0 - 8.0)
    lat_e = np.clip(lat, 8.0, 22.0)
    east_bound = np.where(
        lat <= 22.0,
        78.0 + (91.0 - 78.0) * (lat_e - 8.0) / (22.0 - 8.0),
        91.0 + (lat - 22.0) * 1.5,  # Bengal/Bangladesh coast bulging east
    )
    peninsula = in_peninsula_lat & (lon >= west_bound) & (lon <= east_bound)
    land |= peninsula

    # Sri Lanka: a small island south of the peninsula tip.
    sri_lanka = ((lat - 7.5) ** 2 / 1.3**2 + (lon - 80.7) ** 2 / 1.0**2) <= 1.0
    land |= sri_lanka

    # Andaman & Nicobar chain: a broken line of small islands.
    andaman_strip = (lat >= 6.0) & (lat <= 14.0) & (np.abs(lon - 93.0) < 0.35)
    andaman_islands = andaman_strip & (np.sin(lat * 3.2) > -0.2)
    land |= andaman_islands

    # A couple of tiny Lakshadweep/Maldives-like dots for texture.
    for dot_lat, dot_lon in ((10.5, 72.7), (6.0, 73.1)):
        land |= ((lat - dot_lat) ** 2 + (lon - dot_lon) ** 2) <= 0.03**2

    return ~land  # ocean mask


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------


def _smooth_random_field(
    rng: np.random.Generator, shape: Tuple[int, int], smoothing: int = 9
) -> np.ndarray:
    """A spatially-correlated pseudo-random field in roughly [-1, 1].

    Built with a simple repeated box-blur (no extra dependency needed)
    over white noise, then rescaled. Used for weather-like/cloud-like
    noise textures rather than pixel-independent noise.
    """
    field = rng.standard_normal(shape)
    kernel = np.ones(smoothing) / smoothing
    for _ in range(3):
        field = np.apply_along_axis(lambda m: np.convolve(m, kernel, mode="same"), 0, field)
        field = np.apply_along_axis(lambda m: np.convolve(m, kernel, mode="same"), 1, field)
    peak = np.max(np.abs(field))
    return field / peak if peak > 0 else field


def _season_frac(day_of_year: np.ndarray | float, period_days: float = 365.25) -> np.ndarray:
    """Fractional position in the annual cycle, in [0, 1)."""
    return (np.asarray(day_of_year, dtype=float) % period_days) / period_days


@dataclass(frozen=True)
class Eddy:
    """A single Gaussian mesoscale-eddy-like anomaly."""

    lat0: float
    lon0: float
    radius_deg: float
    amplitude_m: float  # signed: + anticyclonic (warm-core), - cyclonic (cold-core)
    drift_lon_per_step: float  # westward propagation per time step (deg)


def _make_eddies(rng: np.random.Generator, n_eddies: int, grid: OceanGrid) -> list[Eddy]:
    lat_min, lat_max, lon_min, lon_max = grid.bounds
    # Guarantee a mix of cyclonic (cold-core, -) and anticyclonic (warm-core,
    # +) eddies rather than leaving the sign split to chance, which would
    # occasionally (im)plausibly produce an all-one-sign eddy field.
    signs = np.array([1.0, -1.0] * ((n_eddies + 1) // 2))[:n_eddies]
    rng.shuffle(signs)

    eddies = []
    for sign in signs:
        lat0 = rng.uniform(lat_min + 2, lat_max - 4)
        lon0 = rng.uniform(lon_min + 8, lon_max - 8)
        radius = rng.uniform(1.2, 3.0)  # degrees (~130-330 km)
        amp = rng.uniform(0.08, 0.22) * sign
        drift = rng.uniform(0.15, 0.5)  # mesoscale eddies drift westward
        eddies.append(Eddy(lat0, lon0, radius, amp, drift))
    return eddies


def _eddy_field(eddies: list, lat_grid: np.ndarray, lon_grid: np.ndarray, t: int) -> np.ndarray:
    field = np.zeros(lat_grid.shape, dtype=np.float64)
    for e in eddies:
        lon_t = e.lon0 - e.drift_lon_per_step * t
        d2 = (lat_grid - e.lat0) ** 2 + (lon_grid - lon_t) ** 2
        field += e.amplitude_m * np.exp(-d2 / (2 * e.radius_deg**2))
    return field


# ---------------------------------------------------------------------------
# Field generators
# ---------------------------------------------------------------------------


def generate_sla(grid: OceanGrid, eddies: list, n_time: int) -> np.ndarray:
    """Sea Level Anomaly: dominated by drifting Gaussian eddies, near-zero mean."""
    out = np.empty((n_time, *grid.shape), dtype=np.float32)
    for t in range(n_time):
        out[t] = _eddy_field(eddies, grid.lat_grid, grid.lon_grid, t)
    return out


def generate_sst(
    grid: OceanGrid, sla: np.ndarray, rng: np.random.Generator, day_of_year: np.ndarray
) -> np.ndarray:
    """Sea Surface Temperature: tropical warm base, monsoon seasonal cycle,
    upwelling-driven cooling off the Arabian Sea western boundary in
    summer monsoon, eddy-correlated anomaly (+eddy=warm core), noise.
    """
    n_time = sla.shape[0]
    lat, lon = grid.lat_grid, grid.lon_grid
    out = np.empty((n_time, *grid.shape), dtype=np.float32)

    base = 29.5 - 0.12 * (lat - 5.0)  # warm equatorward, cooler poleward
    for t in range(n_time):
        frac = _season_frac(day_of_year[t])
        seasonal = 1.2 * np.sin(2 * np.pi * (frac - 0.15))  # peaks ~ pre-monsoon (May)

        # Somali/Omani coastal upwelling: cooling near western boundary
        # (low lon), strongest during the SW monsoon (Jun-Sep, frac ~0.45-0.75).
        monsoon_strength = max(0.0, np.sin(2 * np.pi * (frac - 0.45)))
        upwelling = -2.5 * monsoon_strength * np.exp(-((lon - 52.0) ** 2) / (2 * 6.0**2))

        eddy_anom = 2.0 * sla[t]  # warm-core (+SLA) / cold-core (-SLA)
        noise = 0.25 * _smooth_random_field(rng, grid.shape)

        out[t] = base + seasonal + upwelling + eddy_anom + noise
    return out


def generate_sss(
    grid: OceanGrid, sla: np.ndarray, rng: np.random.Generator, day_of_year: np.ndarray
) -> np.ndarray:
    """Sea Surface Salinity: saltier Arabian Sea (west, evaporation-driven),
    fresher Bay of Bengal (east, river-runoff/monsoon-rain driven), with a
    monsoon-season freshening pulse on the Bay of Bengal side.
    """
    n_time = sla.shape[0]
    lon = grid.lon_grid
    out = np.empty((n_time, *grid.shape), dtype=np.float32)

    lon_min, lon_max = grid.bounds[2], grid.bounds[3]
    lon_frac = (lon - lon_min) / (lon_max - lon_min)  # 0 west .. 1 east
    base = 36.5 - 3.5 * lon_frac  # ~36.5 psu Arabian Sea -> ~33 psu Bay of Bengal

    for t in range(n_time):
        frac = _season_frac(day_of_year[t])
        monsoon_strength = max(0.0, np.sin(2 * np.pi * (frac - 0.45)))
        bay_freshening = -1.2 * monsoon_strength * lon_frac  # stronger toward the east
        eddy_anom = -0.3 * sla[t]
        noise = 0.08 * _smooth_random_field(rng, grid.shape)
        out[t] = base + bay_freshening + eddy_anom + noise
    return out


def generate_winds(
    grid: OceanGrid, rng: np.random.Generator, day_of_year: np.ndarray
) -> Tuple[np.ndarray, np.ndarray]:
    """U/V wind: idealised Indian-monsoon reversal — strong southwesterly
    flow Jun-Sep, weaker northeasterly flow Dec-Feb, plus synoptic noise.
    """
    n_time = len(day_of_year)
    u = np.empty((n_time, *grid.shape), dtype=np.float32)
    v = np.empty((n_time, *grid.shape), dtype=np.float32)

    for t in range(n_time):
        frac = _season_frac(day_of_year[t])
        # Single annual harmonic: positive (SW monsoon) around Jul (frac~0.55),
        # negative (NE monsoon, weaker) around Jan (frac~0.04).
        monsoon = np.sin(2 * np.pi * (frac - 0.3))
        u_bg = 6.0 * monsoon
        v_bg = 4.0 * monsoon
        synoptic_u = 1.5 * _smooth_random_field(rng, grid.shape, smoothing=13)
        synoptic_v = 1.5 * _smooth_random_field(rng, grid.shape, smoothing=13)
        u[t] = u_bg + synoptic_u
        v[t] = v_bg + synoptic_v
    return u, v


def generate_currents(
    grid: OceanGrid, sla: np.ndarray, day_of_year: np.ndarray, rng: np.random.Generator
) -> Tuple[np.ndarray, np.ndarray]:
    """U/V surface currents: an approximate geostrophic response to the SLA
    field, plus a seasonally-reversing background jet (Somali-Current-like
    western-boundary intensification during the SW monsoon), plus noise.
    """
    n_time = sla.shape[0]
    lat, lon = grid.lat_grid, grid.lon_grid
    lat_rad = np.deg2rad(lat)
    dlat_rad = np.deg2rad(grid.resolution)
    dlon_rad = np.deg2rad(grid.resolution)
    f = 2 * EARTH_OMEGA * np.sin(lat_rad)
    f = np.where(np.abs(f) < 1e-6, 1e-6, f)  # guard divide-by-zero (not hit in this domain)

    u = np.empty((n_time, *grid.shape), dtype=np.float32)
    v = np.empty((n_time, *grid.shape), dtype=np.float32)

    lon_min = grid.bounds[2]
    western_boundary_weight = np.exp(-(lon - lon_min) / 8.0)  # decays eastward

    for t in range(n_time):
        d_sla_dlat = np.gradient(sla[t].astype(np.float64), axis=0) / dlat_rad
        d_sla_dlon = np.gradient(sla[t].astype(np.float64), axis=1) / dlon_rad
        d_sla_dy = d_sla_dlat / EARTH_RADIUS_M
        d_sla_dx = d_sla_dlon / (EARTH_RADIUS_M * np.cos(lat_rad))

        u_geo = -(GRAVITY / f) * d_sla_dy
        v_geo = (GRAVITY / f) * d_sla_dx

        frac = _season_frac(day_of_year[t])
        monsoon = np.sin(2 * np.pi * (frac - 0.3))
        u_bg = 0.5 * monsoon * western_boundary_weight
        v_bg = 0.3 * monsoon * western_boundary_weight

        noise = 0.03 * _smooth_random_field(rng, grid.shape)
        u[t] = u_geo + u_bg + noise
        v[t] = v_geo + v_bg + noise

    return u, v


def generate_subsurface_temperature(
    grid: OceanGrid,
    depths: list,
    sst: np.ndarray,
    sla: np.ndarray,
    day_of_year: np.ndarray,
    rng: np.random.Generator,
) -> np.ndarray:
    """Subsurface temperature at every configured depth: a tanh thermocline
    profile between the (already-generated) SST and an abyssal temperature,
    with a thermocline depth that shoals in winter monsoon (convective
    mixing) and deepens in summer, and is further perturbed by eddies
    (anticyclonic/warm-core eddies deepen the thermocline, cyclonic ones
    shoal it) — a simple, deliberately illustrative analogue of real
    eddy-thermocline interaction.
    """
    n_time = sst.shape[0]
    depths_arr = np.asarray(depths, dtype=np.float64)
    deep_temp = 4.0  # degC abyssal reference

    out = np.empty((n_time, len(depths), *grid.shape), dtype=np.float32)

    for t in range(n_time):
        frac = _season_frac(day_of_year[t])
        # Winter (NE monsoon, frac~0.0-0.15) convective mixing -> shallow
        # mixed layer/thermocline; summer stratification -> deeper.
        seasonal_mld = 30.0 * np.sin(2 * np.pi * (frac - 0.55))
        thermocline_depth = 110.0 + seasonal_mld - 60.0 * sla[t]
        thermocline_depth = np.clip(thermocline_depth, 40.0, 220.0)
        thermocline_width = 35.0 + 5.0 * _smooth_random_field(rng, grid.shape)

        for di, z in enumerate(depths_arr):
            shape_fn = 0.5 * (1 - np.tanh((z - thermocline_depth) / thermocline_width))
            profile = deep_temp + (sst[t] - deep_temp) * shape_fn
            noise = 0.15 * _smooth_random_field(rng, grid.shape)
            out[t, di] = profile + noise

    return out


# ---------------------------------------------------------------------------
# Missing-data / QC gaps
# ---------------------------------------------------------------------------


def _cloud_like_gap_mask(
    rng: np.random.Generator, shape: Tuple[int, int], missing_fraction: float
) -> np.ndarray:
    """Boolean mask, True where data is MISSING, in spatially-correlated
    'cloud swath'-like patches rather than independent per-pixel dropout.
    """
    field = _smooth_random_field(rng, shape, smoothing=15)
    # Threshold chosen (numerically, per-call) so the missing fraction is
    # approximately `missing_fraction` of the field.
    threshold = np.quantile(field, 1.0 - missing_fraction)
    return field >= threshold


def apply_missing_values(
    data: Dict[str, np.ndarray],
    ocean_mask: np.ndarray,
    rng: np.random.Generator,
    surface_missing_frac: float = 0.12,
    subsurface_missing_frac: float = 0.55,
) -> None:
    """Mask land everywhere (NaN) and punch realistic-looking gaps into the
    ocean points too: light cloud-like gaps for gridded surface fields,
    heavier gaps for subsurface temperature (ARGO float coverage is far
    sparser than satellite swath coverage). Modifies `data` in place.
    """
    land_mask = ~ocean_mask
    surface_vars = ("sst", "sss", "sla", "u_current", "v_current", "u_wind", "v_wind")

    for name in surface_vars:
        arr = data[name]
        for t in range(arr.shape[0]):
            gaps = _cloud_like_gap_mask(rng, arr.shape[1:], surface_missing_frac)
            arr[t][land_mask | gaps] = np.nan

    subsurface = data["subsurface_temp"]
    for t in range(subsurface.shape[0]):
        for di in range(subsurface.shape[1]):
            gaps = _cloud_like_gap_mask(rng, subsurface.shape[2:], subsurface_missing_frac)
            subsurface[t, di][land_mask | gaps] = np.nan


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------


def generate_demo_dataset(
    environment: str = "demo", n_time: int = DEFAULT_N_TIME, seed: int | None = None
) -> Tuple[Dict[str, np.ndarray], dict]:
    """Generate the full synthetic demo dataset and its metadata dict."""
    config = load_config(environment)
    seed = config.demo.seed if seed is None else seed
    rng = np.random.default_rng(seed)

    grid = create_ocean_grid(config.domain)
    depths = list(config.depths)

    timestamps = [DEFAULT_START_DATE + timedelta(days=30.44 * i) for i in range(n_time)]
    day_of_year = np.array([ts.timetuple().tm_yday for ts in timestamps], dtype=float)

    ocean_mask = build_land_ocean_mask(grid.lat_grid, grid.lon_grid)

    eddies = _make_eddies(rng, n_eddies=6, grid=grid)
    sla = generate_sla(grid, eddies, n_time)
    sst = generate_sst(grid, sla, rng, day_of_year)
    sss = generate_sss(grid, sla, rng, day_of_year)
    u_wind, v_wind = generate_winds(grid, rng, day_of_year)
    u_current, v_current = generate_currents(grid, sla, day_of_year, rng)
    subsurface_temp = generate_subsurface_temperature(grid, depths, sst, sla, day_of_year, rng)

    data = {
        "sst": sst,
        "sss": sss,
        "sla": sla,
        "u_current": u_current,
        "v_current": v_current,
        "u_wind": u_wind,
        "v_wind": v_wind,
        "subsurface_temp": subsurface_temp,
    }
    apply_missing_values(data, ocean_mask, rng)

    data["land_mask"] = ocean_mask  # keep the name "land_mask", values True=ocean (documented)
    data["latitude"] = grid.latitudes.astype(np.float32)
    data["longitude"] = grid.longitudes.astype(np.float32)
    data["depth"] = np.asarray(depths, dtype=np.float32)
    data["time"] = np.array([ts.strftime("%Y-%m-%d") for ts in timestamps])

    metadata = {
        "data_mode": DATA_MODE,
        "disclaimer": DISCLAIMER,
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "generator": "scripts/create_demo_data.py",
        "project": "NEER",
        "problem_id": "SIH26066",
        "organization": "MoES / INCOIS",
        "seed": int(seed),
        "environment": environment,
        "domain": {
            "lat_min": config.domain.lat_min,
            "lat_max": config.domain.lat_max,
            "lon_min": config.domain.lon_min,
            "lon_max": config.domain.lon_max,
            "resolution_deg": config.domain.resolution,
        },
        "grid_shape": {"n_lat": grid.shape[0], "n_lon": grid.shape[1]},
        "depths_m": depths,
        "n_time_steps": n_time,
        "time_range": [data["time"][0], data["time"][-1]],
        "variables": {
            "sst": {"dims": ["time", "lat", "lon"], "units": "degC", "description": "Sea surface temperature (synthetic)"},
            "sss": {"dims": ["time", "lat", "lon"], "units": "psu", "description": "Sea surface salinity (synthetic)"},
            "sla": {"dims": ["time", "lat", "lon"], "units": "m", "description": "Sea level anomaly (synthetic)"},
            "u_current": {"dims": ["time", "lat", "lon"], "units": "m/s", "description": "Zonal surface current (synthetic)"},
            "v_current": {"dims": ["time", "lat", "lon"], "units": "m/s", "description": "Meridional surface current (synthetic)"},
            "u_wind": {"dims": ["time", "lat", "lon"], "units": "m/s", "description": "Zonal wind (synthetic)"},
            "v_wind": {"dims": ["time", "lat", "lon"], "units": "m/s", "description": "Meridional wind (synthetic)"},
            "subsurface_temp": {"dims": ["time", "depth", "lat", "lon"], "units": "degC", "description": "Subsurface temperature at all 15 target depths (synthetic)"},
            "land_mask": {"dims": ["lat", "lon"], "units": "bool", "description": "True = ocean, False = land (schematic, hand-built approximation, not a real coastline product)"},
        },
        "missing_values": "NaN over land and over synthetic gap patches (cloud-like for surface fields, sparser ARGO-like coverage for subsurface_temp)",
    }
    return data, metadata


def save_dataset(data: Dict[str, np.ndarray], metadata: dict, output_dir: Path) -> Tuple[Path, Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    npz_path = output_dir / "neer_demo_ocean_dataset.npz"
    meta_path = output_dir / "neer_demo_metadata.json"

    np.savez_compressed(npz_path, **data)
    with open(meta_path, "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2)

    return npz_path, meta_path


# ---------------------------------------------------------------------------
# Verification
# ---------------------------------------------------------------------------


def verify_dataset(npz_path: Path, meta_path: Path) -> None:
    """Reload the saved files and sanity-check shapes, dtypes, data_mode,
    and the presence of missing values / masking. Raises AssertionError
    on any failed check.
    """
    with open(meta_path, "r", encoding="utf-8") as f:
        metadata = json.load(f)

    assert metadata["data_mode"] == DATA_MODE, "data_mode must be DEMO_SYNTHETIC"
    assert "disclaimer" in metadata and metadata["disclaimer"], "disclaimer missing"
    assert "satellite" not in metadata["disclaimer"].lower() or "not" in metadata["disclaimer"].lower()

    npz = np.load(npz_path, allow_pickle=False)
    n_lat = metadata["grid_shape"]["n_lat"]
    n_lon = metadata["grid_shape"]["n_lon"]
    n_time = metadata["n_time_steps"]
    n_depth = len(metadata["depths_m"])

    expected_shapes = {
        "sst": (n_time, n_lat, n_lon),
        "sss": (n_time, n_lat, n_lon),
        "sla": (n_time, n_lat, n_lon),
        "u_current": (n_time, n_lat, n_lon),
        "v_current": (n_time, n_lat, n_lon),
        "u_wind": (n_time, n_lat, n_lon),
        "v_wind": (n_time, n_lat, n_lon),
        "subsurface_temp": (n_time, n_depth, n_lat, n_lon),
        "land_mask": (n_lat, n_lon),
        "latitude": (n_lat,),
        "longitude": (n_lon,),
        "depth": (n_depth,),
        "time": (n_time,),
    }

    for name, shape in expected_shapes.items():
        assert name in npz, f"missing array: {name}"
        assert npz[name].shape == shape, f"{name} shape {npz[name].shape} != expected {shape}"

    land_mask = npz["land_mask"]
    assert land_mask.dtype == bool, "land_mask must be boolean"
    assert 0 < land_mask.mean() < 1, "land_mask should contain both land and ocean points"

    # Land points must be NaN in every surface field, at every time step.
    land_points = ~land_mask
    assert land_points.sum() > 0, "expected at least one land point in the synthetic mask"
    assert np.isnan(npz["sst"][0][land_points]).all(), "land points must be NaN in sst"

    # Ocean points should have *some* missing values (gaps) but not be
    # entirely missing.
    ocean_sst_t0 = npz["sst"][0][land_mask]
    frac_missing = np.isnan(ocean_sst_t0).mean()
    assert 0.0 < frac_missing < 0.9, f"unexpected ocean-point missing fraction for sst: {frac_missing:.2f}"

    # Subsurface temperature should decrease with depth on average
    # (thermocline structure) at ocean points, ignoring NaNs.
    subsurface = npz["subsurface_temp"]
    # Allow a small tolerance for noise averaging in the near-isothermal
    # abyssal layer (deep levels hover around the same reference
    # temperature with independent per-depth noise).
    mean_by_depth = np.nanmean(subsurface[:, :, land_mask], axis=(0, 2))
    assert np.all(np.diff(mean_by_depth) <= 0.05), "mean temperature should not increase with depth"

    # depths must match config exactly and be ascending
    depths = npz["depth"]
    assert list(depths) == sorted(depths), "depths must be ascending"
    assert len(depths) == 15, f"expected 15 depth levels, got {len(depths)}"

    logger.info(
        "Verification OK: shapes match, data_mode=%s, land_mask ocean_frac=%.3f, "
        "sst ocean missing_frac(t=0)=%.3f, thermocline mean profile is non-increasing with depth.",
        metadata["data_mode"],
        land_mask.mean(),
        frac_missing,
    )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--environment", default="demo", choices=["base", "demo", "development", "production"])
    parser.add_argument("--n-time", type=int, default=DEFAULT_N_TIME, help="Number of time steps to generate")
    parser.add_argument("--seed", type=int, default=None, help="Override the seed from configs/*.yaml")
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=PROJECT_ROOT / "data" / "demo",
        help="Directory to write the demo dataset into (default: data/demo)",
    )
    args = parser.parse_args()

    logger.info("Generating synthetic demo dataset (data_mode=%s)...", DATA_MODE)
    data, metadata = generate_demo_dataset(
        environment=args.environment, n_time=args.n_time, seed=args.seed
    )

    logger.info("Saving dataset to %s ...", args.output_dir)
    npz_path, meta_path = save_dataset(data, metadata, args.output_dir)
    logger.info("Wrote %s and %s", npz_path, meta_path)

    logger.info("Verifying generated dataset...")
    verify_dataset(npz_path, meta_path)
    logger.info("Done. This dataset is SYNTHETIC (data_mode=DEMO_SYNTHETIC) — not real observational data.")


if __name__ == "__main__":
    main()
